/* confdefs.h */
#define PACKAGE_NAME "Dos9"
#define PACKAGE_TARNAME "Dos9"
#define PACKAGE_VERSION "216.1"
#define PACKAGE_STRING "Dos9 216.1"
#define PACKAGE_BUGREPORT "darkbatcher@dos9.org"
#define PACKAGE_URL "http://www.dos9.org/"
#define HOST "x86_64-w64-mingw32"
#define PACKAGE "Dos9"
#define VERSION "216.1"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define LT_OBJDIR ".libs/"
#define STDC_HEADERS 1
#define HAVE_ICONV 1
#define HAVE_LIBM 1
