# Overall Dos9 suite Makefile, The Dos9 Project (c) Darkbatcher
# 2010-2013
#
# This is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
#
# This files generates translations while compiling
#

PO_BUILD=$$(ls po/)
SHARE_DIR=./share/locale

MSGFMT = /usr/bin/msgfmt
XGETTEXT = /usr/bin/xgettext
MSGMERGE = /usr/bin/msgmerge
prefix = /usr/local

all:
dist:
distdir:

install:
	cp Dos9_Auto.bat $(prefix)/
	cp -R cmd $(prefix)/
